"""GENERATED by tools/gen_settings.py — do not edit by hand.

Groups, labels and help text come from scripts/virt_team_launcher.py
(_SETTING_GROUPS, _SETTING_HELP), so this screen cannot drift from the thing
it configures. Re-run the generator after either changes.
"""

SETTING_GROUPS = [('What the team produces',
  [{'key': 'extra_formats',
    'label': 'docx export',
    'kind': 'toggle',
    'options': (),
    'value': False,
    'what': 'Also render deliverables as .docx alongside the .md + .html every engagement '
            'already produces. For sharing with people who live in Word.',
    'off': 'Off: markdown and HTML only.',
    'needs': "needs python-docx — the installer's 'Document output' option"},
   {'key': 'regulatory_citations',
    'label': 'regulatory citations',
    'kind': 'toggle',
    'options': (),
    'value': True,
    'what': 'Each requirement in the RTM carries the specific obligation it serves, so an '
            'alert traces back to the rule that justifies it.',
    'off': 'Off: the obligation link is recorded as DECLINED, never silently dropped - the '
           'rest of the trace still holds.',
    'needs': ''},
   {'key': 'evidence_room',
    'label': 'evidence room at close',
    'kind': 'toggle',
    'options': (),
    'value': True,
    'what': 'Assembles one self-contained HTML pack at close from evidence the engagement '
            'already produced - for handing to an auditor.',
    'off': 'Off (the default): whether a project wants an auditor-facing pack is a governance '
           'decision, so it is never created unasked.',
    'needs': ''},
   {'key': 'standards_critique',
    'label': 'standards critique',
    'kind': 'toggle',
    'options': (),
    'value': False,
    'what': 'Adds a second, independent critic pass over an already-finished deliverable, '
            'judged against the named standard, before handover.',
    'off': 'Off (the default): the normal review gates still apply. This is a full extra pass, '
           'not a universal expectation.',
    'needs': ''}]),
 ('How much work it does',
  [{'key': 'qa_depth',
    'label': 'qa depth',
    'kind': 'choice',
    'options': ('auto', 'quick', 'deep'),
    'value': 'auto',
    'what': 'How much INDEPENDENT QA a build buys. auto reads the work; quick narrows what '
            'gets written and always closes PARTIAL; deep is the full pass; audit is the '
            'heaviest.',
    'off': 'There is no off: QA running, and being independent of whoever wrote the code, is '
           'not tierable - only its breadth is.',
    'needs': ''},
   {'key': 'large_context_review_split',
    'label': 'large-context review split',
    'kind': 'toggle',
    'options': (),
    'value': True,
    'what': 'Splits a big review into several passes instead of one call, so a large findings '
            'set cannot blow the write cap or time out mid-review.',
    'off': 'Off: one delegated review call. Worth turning on if reviews here keep hitting the '
           '~8-finding threshold.',
    'needs': ''},
   {'key': 'parallel_dispatch_via_workflow',
    'label': 'parallel dispatch (Workflow)',
    'kind': 'toggle',
    'options': (),
    'value': False,
    'what': "Independent review passes fan out through the Workflow tool's deterministic "
            'parallel dispatch rather than batched Task calls, which did not stick reliably.',
    'off': 'Off: passes run one after another. Slower, but no Workflow dependency.',
    'needs': ''}]),
 ('Running unattended',
  [{'key': 'autonomous_mode',
    'label': 'autonomous mode offered',
    'kind': 'toggle',
    'options': (),
    'value': True,
    'what': 'Whether an unattended run may be OFFERED at all - from a Jira ticket [j] or a '
            'typed request [n]. This is a kill switch, not an enabler: it is already on.',
    'off': 'Off removes the option from this project entirely. On does not start anything '
           "unattended by itself - see 'start work unattended' for that.",
    'needs': ''},
   {'key': 'autonomous_default',
    'label': 'start work unattended',
    'kind': 'toggle',
    'options': (),
    'value': False,
    'what': 'Arms the unattended toggle for new work, so a run you were going to start '
            'unattended starts that way without reaching for Ctrl-T each time.',
    'off': 'It changes the default ANSWER, never removes the question: an armed run still '
           'stops at the pre-flight, where you attest the data, allow code and set the '
           'ceiling. Off by default - unattended stays opt-in, per project.',
    'needs': ''},
   {'key': 'new_window',
    'label': 'open the session in a new window',
    'kind': 'toggle',
    'options': (),
    'value': False,
    'what': 'Opens the Claude session in its own terminal window - attended or unattended - so '
            "this launcher survives to show the workflow and the run's status.",
    'off': 'OFF by default for now. Without it the session replaces this screen, which is what '
           'made the workflow hard to watch. No windowed terminal means it opens here anyway.',
    'needs': ''}]),
 ('Understanding the codebase',
  [{'key': 'map_skeleton',
    'label': 'codebase-map skeleton',
    'kind': 'toggle',
    'options': (),
    'value': True,
    'what': 'Seeds a starter docs/codebase-map.md for a project that has none, so the team has '
            'a map to curate instead of a blank page.',
    'off': 'Off: the map is only ever written by hand.',
    'needs': ''},
   {'key': 'document_map',
    'label': 'document map',
    'kind': 'toggle',
    'options': (),
    'value': False,
    'what': 'Lets the team inventory a documentation tree first - filenames, dates and heading '
            'outlines - so it knows what exists before opening anything.',
    'off': 'On by default at machine and project level. Off means documents get opened at '
           'random instead, which costs more and misses things.',
    'needs': ''},
   {'key': 'data_profiling',
    'label': 'data profiling tools',
    'kind': 'toggle',
    'options': (),
    'value': True,
    'what': 'Lets the team run profile_temporal (gaps, freshness, cadence over time) and '
            'tag_columns (what each column means) on a dataset. Both emit counts and dates '
            'only - never a record.',
    'off': 'On by default: it is SAFER than the alternative, which is an agent reading rows '
           'into context. Off only where no tool may touch client data at all.',
    'needs': ''}]),
 ('Jira',
  [{'key': 'jira',
    'label': 'jira',
    'kind': 'toggle',
    'options': (),
    'value': False,
    'what': 'Whether the team WRITES to your tracker itself. On: it raises ONE issue per '
            'engagement at open, after you approve a plan naming it, then comments as work '
            'moves and posts the summary at close.',
    'off': 'Off does NOT hide Jira. [j] still works: it starts from a ticket and reports back '
           'to that one ticket, without ever raising issues of its own.',
    'needs': ''},
   {'key': 'integrations.jira.mirror',
    'label': 'jira mirror',
    'kind': 'choice',
    'options': ('close-only', 'live'),
    'value': 'close-only',
    'what': 'WHEN tracker updates are posted. close-only waits until the end; live comments as '
            'phases change.',
    'off': 'Only bites when jira write-back is on. Work started from a ticket tracks live '
           'regardless, unless you set close-only here.',
    'needs': ''}]),
 ('Speed',
  [{'key': 'probe_cache',
    'label': 'probe pre-cache at go',
    'kind': 'toggle',
    'options': (),
    'value': True,
    'what': 'Computes the engage probe HERE, outside the session, and caches it - so opening '
            'an engagement skips work that takes minutes on a locked-down box.',
    'off': 'Pure accelerator: a missing or stale cache just runs the live probe, so nothing '
           'breaks either way.',
    'needs': ''},
   {'key': 'guard_daemon',
    'label': 'guard daemon',
    'kind': 'toggle',
    'options': (),
    'value': True,
    'what': 'Runs the safety guards in one persistent process instead of starting a fresh '
            'interpreter for every hook. Same guard code, same decisions - only the startup '
            'cost differs (~625ms vs ~211ms per call on Windows).',
    'off': 'On by default at machine and project level. Off falls back to a process per call: '
           'slower, never less safe.',
    'needs': ''},
   {'key': 'env_tuning',
    'label': 'env tuning',
    'kind': 'toggle',
    'options': (),
    'value': True,
    'what': "Writes tuned timeouts and a 1-hour prompt-cache TTL into this project's "
            '.claude/settings.json - fewer timeouts, and cache that survives a thinking pause.',
    'off': "Not applied: Claude Code's own defaults are used.",
    'needs': ''}])]
