#!/bin/bash
# Install the repo's opt-in AI-review git hooks. Run once:
#   bash scripts/install-git-hooks.sh                # both hooks
#   bash scripts/install-git-hooks.sh pre-commit     # just the commit gate
#   bash scripts/install-git-hooks.sh pre-push       # just the push review
#
# The severity-blocking gate is adapted from turingmind-code-review (MIT) - see
# THIRD-PARTY-LICENSES.md. Both hooks are OFF until installed, and an LLM in the git path is
# slow - bypass any single run with `--no-verify`.
#
# INSTALL ORDER (T-4, 2026-09-12 test-quality audit). This script and the pre-commit FRAMEWORK
# (`pre-commit install`, driven by .pre-commit-config.yaml - gitleaks, dlp-blocked-terms,
# block-raw-data, pytest) both ultimately want to own the one file `.git/hooks/pre-commit`.
# They are not merged automatically, so:
#   - Recommended: run `pre-commit install` FIRST, then this script SECOND. The framework's
#     own installer already refuses to clobber a hook it doesn't recognise (it exits with
#     "Hook script ... already exists" unless you pass `--overwrite`) - so if you want the
#     framework's deterministic gates AND intend to add the AI review gate, doing this in
#     that order surfaces the collision instead of hiding it.
#   - This script did the opposite silently until this fix: `install -m 0755` has no such
#     check, so running it after `pre-commit install` used to overwrite the framework's
#     hook - gitleaks/dlp/raw-data/pytest would silently stop running on commit - with no
#     warning and nothing catching it. It now refuses instead (see install_hook below).
#   - Only one pre-commit hook file can run at a time either way: this script does not chain
#     into the framework's hook, and the framework does not know about this one. Choosing
#     between them (or accepting the refusal and moving the other one aside deliberately,
#     e.g. `mv .git/hooks/pre-commit .git/hooks/pre-commit.pre-commit-framework`) is a human
#     decision this script will not make silently.
set -euo pipefail
root=$(git rev-parse --show-toplevel)
src="$root/scripts/git-hooks"
dst=$(git rev-parse --git-path hooks)   # worktree/submodule-safe
which=${1:-all}

# Our own hooks carry this marker comment (see scripts/git-hooks/pre-commit,
# scripts/git-hooks/pre-push) - re-running this installer over its own prior output must
# stay a silent no-op/upgrade, never a refusal.
OURS_MARKER="compliance-surveillance-team"

install_hook() {
  local name="$1"
  local dest="$dst/$name"
  if [ -f "$dest" ] && ! grep -q "$OURS_MARKER" "$dest" 2>/dev/null; then
    echo "❌ Refusing to overwrite $dest: it was not installed by this script." >&2
    if grep -q "generated by pre-commit" "$dest" 2>/dev/null; then
      echo "   It looks like the pre-commit FRAMEWORK's hook (gitleaks / dlp-blocked-terms /" >&2
      echo "   block-raw-data / pytest gates from .pre-commit-config.yaml)." >&2
    fi
    echo "   Overwriting it would silently drop whatever runs there now - no merge, no warning" >&2
    echo "   at commit time. Move it aside first if you want both gates available:" >&2
    echo "     mv \"$dest\" \"$dest.pre-commit-framework\"" >&2
    echo "   Or force this install (loses the existing hook):" >&2
    echo "     VIRT_SURV_FORCE_HOOK=1 bash scripts/install-git-hooks.sh $name" >&2
    return 1
  fi
  install -m 0755 "$src/$name" "$dest"
  echo "✅ Installed $name -> $dest"
}

if [ "${VIRT_SURV_FORCE_HOOK:-}" = "1" ]; then
  install_hook() {
    local name="$1"
    install -m 0755 "$src/$name" "$dst/$name"
    echo "✅ Installed $name -> $dst/$name (forced, VIRT_SURV_FORCE_HOOK=1)"
  }
fi

if [ "$which" = "all" ] || [ "$which" = "pre-commit" ]; then
  install_hook pre-commit
  echo "   Commit gate: BLOCKS on 🔴 Critical or any §5 data-safety finding; 🟠 Warning is advisory."
  echo "   Bypass one commit with: git commit --no-verify"
fi
if [ "$which" = "all" ] || [ "$which" = "pre-push" ]; then
  install_hook pre-push
  echo "   Push review: advisory (does not block). Bypass with: git push --no-verify"
fi

echo
echo "Tip: also run 'pre-commit install' for the deterministic gates"
echo "     (tests, secret scan, no-raw-data) - separate from the AI review gate above."
echo "     See the INSTALL ORDER note at the top of this script for why order matters."
