#!/usr/bin/env python3
"""Generate hash-pinned lock files for the two requirements files (step 7.13, 2026-09-13).

WHY. requirements-dev.txt and requirements-review.txt carry version RANGES and no hashes, so
`pip install -r` fetched whatever PyPI served that day - the same unpinned, unverified class
of download the release binaries used to be. A bank's reviewer treats a wheel and a binary
alike. This writes requirements-dev.lock and requirements-review.lock: every package in the
transitive closure pinned to one version, with `--hash=sha256:` for EVERY file PyPI publishes
for that version (all wheels and the sdist), so `pip install --require-hashes -r <lock>`
works on Linux, macOS and Windows alike and refuses a substituted file anywhere.

HUMAN-RUN, AT RELEASE TIME, WITH NETWORK. Nothing is downloaded: the closure comes from
`pip install --dry-run --report` (pip 23+), resolved once per target platform and unioned
so a Windows-only or macOS-only dependency is not missing from the lock; the digests come
from PyPI's JSON API. It is not runtime tooling for the team, so it is deliberately absent
from the execution gate's allow-list.

    python scripts/pin_python_requirements.py                 # both files
    python scripts/pin_python_requirements.py requirements-dev.txt --check
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import subprocess  # nosec B404 - fixed argv, shell=False, pip's own dry run
import sys
import tempfile
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
_PYPI = "https://pypi.org/pypi/{name}/{version}/json"
# One resolution per platform the installer meets; the union is the lock. `--only-binary`
# is what lets pip resolve for a platform it is not running on; a package published only
# as an sdist makes that resolution fail, in which case the native one alone is used and
# the run says so.
_PLATFORMS = (
    (
        "linux",
        [
            "--platform",
            "manylinux_2_28_x86_64",
            "--platform",
            "manylinux_2_17_x86_64",
            "--platform",
            "manylinux2014_x86_64",
        ],
    ),
    ("windows", ["--platform", "win_amd64"]),
    ("macos", ["--platform", "macosx_11_0_arm64", "--platform", "macosx_10_9_x86_64"]),
)
_DEFAULT_FILES = ("requirements-dev.txt", "requirements-review.txt")


def resolve(requirements: Path, platform_args: list[str] | None, timeout: int = 600) -> dict:
    """{name: version} from one pip dry-run resolution. Raises CalledProcessError."""
    with tempfile.TemporaryDirectory() as tmp:
        report = Path(tmp) / "report.json"
        argv = [
            sys.executable,
            "-m",
            "pip",
            "install",
            "--dry-run",
            "--ignore-installed",
            "--quiet",
            "--report",
            str(report),
            "-r",
            str(requirements),
        ]
        if platform_args:
            argv += ["--only-binary=:all:", "--python-version", "3.12", *platform_args]
        subprocess.run(argv, check=True, capture_output=True, text=True, timeout=timeout)  # nosec B603
        data = json.loads(report.read_text(encoding="utf-8"))
    return {
        item["metadata"]["name"].lower().replace("_", "-"): item["metadata"]["version"]
        for item in data.get("install", [])
    }


def pypi_digests(name: str, version: str, timeout: int = 30) -> list[str]:
    """Every sha256 PyPI publishes for this release: wheels and sdist alike."""
    request = urllib.request.Request(
        _PYPI.format(name=name, version=version), headers={"User-Agent": "virt-surv-it-pin"}
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:  # nosec B310 - fixed https literal
        data = json.loads(response.read().decode("utf-8"))
    return sorted({f["digests"]["sha256"] for f in data.get("urls", []) if f.get("digests")})


def build_lock(requirements: Path) -> tuple[str, list[str]]:
    """The lock text and the warnings produced while building it."""
    warnings: list[str] = []
    pinned: dict[str, str] = resolve(requirements, None)
    for label, args in _PLATFORMS:
        try:
            for name, version in resolve(requirements, args).items():
                if name in pinned and pinned[name] != version:
                    warnings.append(f"{name}: {pinned[name]} natively, {version} for {label}")
                pinned.setdefault(name, version)
        except subprocess.CalledProcessError as exc:
            tail = (exc.stderr or "").strip().splitlines()[-1:] or ["no detail"]
            warnings.append(f"{label} resolution skipped: {tail[0][:120]}")
    lines = [
        f"# Generated by scripts/pin_python_requirements.py from {requirements.name} on "
        f"{_dt.date.today().isoformat()}. Do not edit by hand: change {requirements.name} and",
        "# regenerate. Install with: pip install --require-hashes -r "
        + requirements.stem
        + ".lock",
        "# Every file PyPI publishes for each pinned version is listed, so one lock serves",
        "# Linux, macOS and Windows.",
        "",
    ]
    for name in sorted(pinned):
        version = pinned[name]
        digests = pypi_digests(name, version)
        if not digests:
            warnings.append(f"{name}=={version}: PyPI lists no files (not on PyPI?)")
            continue
        lines.append(f"{name}=={version} \\")
        lines += [
            f"    --hash=sha256:{d}" + (" \\" if i < len(digests) - 1 else "")
            for i, d in enumerate(digests)
        ]
    return "\n".join(lines) + "\n", warnings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("files", nargs="*", default=list(_DEFAULT_FILES))
    parser.add_argument("--check", action="store_true", help="exit 1 if a lock would change")
    args = parser.parse_args(argv)
    rc = 0
    for rel in args.files:
        requirements = (REPO / rel) if not Path(rel).is_absolute() else Path(rel)
        lock = requirements.with_suffix(".lock")
        text, warnings = build_lock(requirements)
        for w in warnings:
            print(f"  ! {w}")
        body = lambda s: "\n".join(x for x in s.splitlines() if not x.startswith("# Generated"))  # noqa: E731
        if args.check:
            current = lock.read_text(encoding="utf-8") if lock.exists() else ""
            changed = body(current) != body(text)
            print(f"{lock.name}: {'DRIFT' if changed else 'current'}")
            rc = rc or (1 if changed else 0)
            continue
        lock.write_text(text, encoding="utf-8")
        print(f"wrote {lock.name} ({text.count('==')} packages)")
    return rc


if __name__ == "__main__":
    sys.exit(main())
